// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7C-sJK-_P43AqxhcFPOPaZhog2LaEAOs',
    appId: '1:298885391226:web:0386cd908143c1defaacc3',
    messagingSenderId: '298885391226',
    projectId: 'p2-abastecimento',
    authDomain: 'p2-abastecimento.firebaseapp.com',
    storageBucket: 'p2-abastecimento.firebasestorage.app',
    measurementId: 'G-KKNQ5K50X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGRF0ObXW8lZ4khe4nJ1xsX-q7IWUAdlI',
    appId: '1:298885391226:android:2c63ed509c71784ffaacc3',
    messagingSenderId: '298885391226',
    projectId: 'p2-abastecimento',
    storageBucket: 'p2-abastecimento.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWHwgiQ6AOnXffXrxITzdGbQe-XfUiPIY',
    appId: '1:298885391226:ios:2a29bab7650022c7faacc3',
    messagingSenderId: '298885391226',
    projectId: 'p2-abastecimento',
    storageBucket: 'p2-abastecimento.firebasestorage.app',
    iosBundleId: 'com.example.p2Andre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWHwgiQ6AOnXffXrxITzdGbQe-XfUiPIY',
    appId: '1:298885391226:ios:2a29bab7650022c7faacc3',
    messagingSenderId: '298885391226',
    projectId: 'p2-abastecimento',
    storageBucket: 'p2-abastecimento.firebasestorage.app',
    iosBundleId: 'com.example.p2Andre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7C-sJK-_P43AqxhcFPOPaZhog2LaEAOs',
    appId: '1:298885391226:web:ae1d6430d636e6ccfaacc3',
    messagingSenderId: '298885391226',
    projectId: 'p2-abastecimento',
    authDomain: 'p2-abastecimento.firebaseapp.com',
    storageBucket: 'p2-abastecimento.firebasestorage.app',
    measurementId: 'G-W4KJH6GWCL',
  );
}
